version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:20.9.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm test
      - run:
          name: Generate Code Coverage
          command: npm run coverage
      - store_artifacts:
          path: /tmp/coverage
