version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm test
      - run:
          name: Generate Code Coverage
          command: npm run coverage
      - store_artifacts:
          path: /tmp/coverage
      - slack/notify:
        channel: '#general'
        context: calculator_assignment_with_orbs
        custom: |
          {
            "blocks": [
              "type": "section",
              "fields": [
                {
                  "type": "plain_text",
                  "text": "This is <> submitting the slack assignment"
                }
              ]
            ]
          }
